# Generated by Django 5.1.3 on 2024-11-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzerias', '0002_rename_name_pizza_text_pizza_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
    ]
